name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t mirzaahmad/python-app .
        docker tag mirzaahmad/python-app mirzaahmad/python-app:latest

    - name: Push Docker image
      run: |
        docker push mirzaahmad/python-app
        docker push mirzaahmad/python-app:latest
